export const headerColumns = [
  { id: 'invoice_id', label: 'INVOICE ID' },
  { id: 'client_id', label: 'CLIENT' },
  { id: 'email_id', label: 'Email' },
  { id: 'date_id', label: 'DATE' },
  { id: 'billed_id', label: 'BILLED', format: (value) => value.toFixed(2) },
  { id: 'status_id', label: 'STATUS' },
  { id: 'action_id', label: 'ACTION' },
];

export const rows = [
  {
    id: 1,
    client: { img: '', name: 'Client A' },
    email: 'a@gmail.com',
    date: '11-11-1111',
    billed: 1200,
    status: 'Paid',
    action: '...',
  },
  {
    id: 2,
    client: { img: '', name: 'Client B' },
    email: 'a@gmail.com',
    date: '11-11-1111',
    billed: 1300,
    status: 'Unpaid',
    action: '...',
  },
  {
    id: 3,
    client: { img: '', name: 'Client C' },
    email: 'a@gmail.com',
    date: '11-11-1111',
    billed: 1400,
    status: 'Refund',
    action: '...',
  },
  {
    id: 4,
    client: { img: '', name: 'Client D' },
    email: 'a@gmail.com',
    date: '11-11-1111',
    billed: 1400,
    status: 'Cancel',
    action: '...',
  },
  {
    id: 5,
    client: { img: '', name: 'Client E' },
    email: 'a@gmail.com',
    date: '11-11-1111',
    billed: 1400,
    status: 'Paid',
    action: '...',
  },
];
